# Generated by Django 5.1.4 on 2024-12-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PowerStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                ("station_type", models.CharField(max_length=50)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                ("storage", models.FloatField(default=0)),
                ("storage_limit", models.FloatField()),
                ("generation_rate", models.FloatField()),
                ("power", models.FloatField()),
                ("engineers", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PowerStationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_type", models.CharField(max_length=50)),
                ("level", models.PositiveSmallIntegerField()),
                ("price_kw", models.FloatField()),
                ("price_tbtc", models.FloatField()),
                ("storage_limit", models.FloatField()),
                ("generation_rate", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_id",
            field=models.BigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
