# Generated by Django 5.1.4 on 2024-12-27 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_powerstation_powerstationconfig_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="powerstation",
            name="engineers",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="generation_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="level",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="power",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="referrer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="core.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="referrer_level_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals_level_2",
                to="core.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="station_type",
            field=models.CharField(default="Boiler house", max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="storage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="storage_limit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="powerstation",
            name="generation_rate",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="powerstation",
            name="level",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="powerstation",
            name="power",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name="powerstation",
            name="station_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="powerstation",
            name="storage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="powerstation",
            name="storage_limit",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="powerstation",
            name="user_id",
            field=models.IntegerField(),
        ),
    ]
