# Generated by Django 5.1.4 on 2024-12-27 16:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_powerstation_engineers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.CharField(max_length=255)),
                ("token_amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("token_contract_address", models.CharField(max_length=255)),
                ("claimed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="PowerStation",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bonus_kw_level_1",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bonus_kw_level_2",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bonus_tbtc_level_1",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bonus_tbtc_level_2",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="kw_wallet",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tbtc_wallet",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.userprofile"
            ),
        ),
    ]
