# Generated by Django 5.1.4 on 2024-12-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_userprofile_battery_balance_userprofile_farm_runtime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ton_wallet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
