# Generated by Django 5.1.4 on 2024-12-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_userprofile_ton_wallet"),
    ]

    operations = [
        migrations.CreateModel(
            name="EngineerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField()),
                ("tap_power", models.FloatField()),
                ("hire_cost", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="GenPowerStationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_type", models.CharField(max_length=50)),
                ("level", models.PositiveSmallIntegerField()),
                ("price_kw", models.FloatField()),
                ("price_tbtc", models.FloatField()),
                ("generation_rate", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="StoragePowerStationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_type", models.CharField(max_length=50)),
                ("level", models.PositiveSmallIntegerField()),
                ("price_kw", models.FloatField()),
                ("price_tbtc", models.FloatField()),
                ("storage_limit", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="PowerStationConfig",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="level",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="ton_wallet",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="engineer_level",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="generation_level",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="kw_per_tap",
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="storage_level",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
