# Generated by Django 5.1.4 on 2025-01-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_repairpowerstationconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ton_wallet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
