# Generated by Django 5.1.4 on 2025-01-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_userprofile_ton_wallet"),
    ]

    operations = [
        migrations.CreateModel(
            name="BufferTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tx_hash", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
            ],
        ),
    ]
