# Generated by Django 5.1.4 on 2025-01-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_buffertransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="kw_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tbtc_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
