# Generated by Django 5.1.4 on 2025-01-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_userprofile_kw_address_userprofile_tbtc_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="nft_string",
            field=models.TextField(blank=True, default=""),
        ),
    ]
