# Generated by Django 5.1.4 on 2025-01-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_userprofile_nft_string"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="started_mining_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
