# Generated by Django 5.1.4 on 2025-01-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_userprofile_started_mining_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsicsCoefs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("coef", models.FloatField(default=1)),
            ],
        ),
    ]
