# Generated by Django 5.1.4 on 2025-01-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_asicscoefs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="storage",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
