# Generated by Django 5.1.4 on 2025-01-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_userprofile_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mining_period",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
