# Generated by Django 5.1.4 on 2025-01-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_userprofile_mining_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="buffertransaction",
            name="success",
            field=models.BooleanField(default=False),
        ),
    ]
