# Generated by Django 5.1.4 on 2025-01-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_buffertransaction_success"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_tbtc_added",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
