# Generated by Django 5.1.4 on 2025-01-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_userprofile_last_tbtc_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="generation_rate",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="power",
            field=models.DecimalField(decimal_places=8, default=100, max_digits=18),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="storage",
            field=models.DecimalField(decimal_places=8, default=10, max_digits=18),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="storage_limit",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
