# Generated by Django 5.1.4 on 2025-01-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_userprofile_generation_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="ton_wallet",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
