# Generated by Django 5.1.4 on 2025-01-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_userprofile_ton_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
