# Generated by Django 5.1.4 on 2025-01-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_userprofile_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="energy",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="generation_level",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="generation_rate",
            field=models.DecimalField(decimal_places=16, default=5, max_digits=36),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="station_type",
            field=models.CharField(default="Boiler house", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="generation_rate",
            field=models.DecimalField(decimal_places=16, default=5, max_digits=36),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="kw_per_tap",
            field=models.FloatField(default=0.025),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="power",
            field=models.DecimalField(decimal_places=16, default=100, max_digits=36),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="storage",
            field=models.DecimalField(decimal_places=16, default=10, max_digits=36),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="storage_limit",
            field=models.DecimalField(decimal_places=16, default=10, max_digits=36),
        ),
    ]
