# Generated by Django 5.1.4 on 2025-01-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_withdrawalrequest_energy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="true_started_mining_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
