# Generated by Django 5.1.4 on 2025-01-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_userprofile_true_started_mining_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmapitem",
            name="item_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата"),
        ),
    ]
