# Generated by Django 5.1.4 on 2025-01-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_userprofile_register_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="storage_level",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
