# Generated by Django 5.1.4 on 2025-01-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_withdrawalrequest_storage_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="tbtc_claimed_period",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="tbtc_claimed_period",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="tbtc_left",
            field=models.FloatField(default=0),
        ),
    ]
