# Generated by Django 5.1.4 on 2025-01-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_userprofile_tbtc_claimed_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bring_bonus_kw_level_1",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bring_bonus_kw_level_2",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bring_bonus_tbtc_level_1",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bring_bonus_tbtc_level_2",
            field=models.FloatField(default=0),
        ),
    ]
