# Generated by Django 5.1.4 on 2025-01-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_userprofile_bring_bonus_kw_level_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="tap_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
