# Generated by Django 5.1.4 on 2025-02-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_userprofile_tap_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="OverheatConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_duration", models.PositiveIntegerField(default=5)),
                ("max_duration", models.PositiveIntegerField(default=15)),
                ("activation_count", models.PositiveIntegerField(default=2)),
                ("activation_period_minutes", models.PositiveIntegerField(default=20)),
                (
                    "taps_before_health_reduction",
                    models.PositiveIntegerField(default=5),
                ),
                ("health_reduction_percentage", models.FloatField(default=1.0)),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="overheated_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
