# Generated by Django 5.1.4 on 2025-02-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_overheatconfig_userprofile_overheated_until"),
    ]

    operations = [
        migrations.RenameField(
            model_name="overheatconfig",
            old_name="health_reduction_percentage",
            new_name="power_reduction_percentage",
        ),
        migrations.RenameField(
            model_name="overheatconfig",
            old_name="taps_before_health_reduction",
            new_name="taps_before_power_reduction",
        ),
        migrations.RemoveField(
            model_name="overheatconfig",
            name="activation_count",
        ),
        migrations.RemoveField(
            model_name="overheatconfig",
            name="activation_period_minutes",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="overheat_energy_collected",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="overheat_goal",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tap_count_since_overheat",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="was_overheated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="overheatconfig",
            name="max_duration",
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name="overheatconfig",
            name="min_duration",
            field=models.PositiveIntegerField(default=15),
        ),
    ]
