# Generated by Django 5.1.4 on 2025-02-08 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0032_rename_health_reduction_percentage_overheatconfig_power_reduction_percentage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="note",
            field=models.CharField(default="withdraw", max_length=255),
        ),
        migrations.CreateModel(
            name="AutoWithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "token_amount_full",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                ("token_amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("token_type", models.CharField(max_length=255)),
                ("claimed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(default="pending", max_length=255)),
                ("tx_id", models.CharField(default="", max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.userprofile",
                    ),
                ),
            ],
        ),
    ]
