# Generated by Django 5.1.4 on 2025-02-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_withdrawalrequest_note_autowithdrawalrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_kw", models.FloatField(default=500)),
                ("min_tbtc", models.FloatField(default=50)),
                ("min_claim", models.FloatField(default=0)),
                ("max_auto_kw", models.FloatField(default=10000)),
                ("max_auto_tbtc", models.FloatField(default=500)),
                ("max_auto_claim", models.FloatField(default=500)),
            ],
        ),
    ]
