# Generated by Django 5.1.4 on 2025-02-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_withdrawalconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="KwCommissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.FloatField()),
            ],
        ),
    ]
