# Generated by Django 5.1.4 on 2025-02-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_kwcommissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kwcommissions",
            options={"ordering": ["-date"]},
        ),
    ]
