# Generated by Django 5.1.4 on 2025-02-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_miningcommissions_tbtccommissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="is_auto",
            field=models.BooleanField(default=False),
        ),
    ]
