# Generated by Django 5.1.4 on 2025-02-12 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_userprofile_last_kw_bonus_claimed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_tbtc_bonus_claimed_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
