# Generated by Django 5.1.4 on 2025-02-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_userprofile_last_tbtc_bonus_claimed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="autostart_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="azot_activated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="azot_counts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="cryo_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="jarvis_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="magnit_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="manager_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="powerbank_activated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
