# Generated by Django 5.1.4 on 2025-02-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_userprofile_autostart_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_powerbank_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="powerbank_max_consume",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="stop_mining_at1",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="stop_mining_at2",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="stop_mining_at3",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="stop_mining_next",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
