# Generated by Django 5.1.4 on 2025-02-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_userprofile_is_powerbank_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalconfig",
            name="wheel_kw_cost",
            field=models.FloatField(default=1500),
        ),
        migrations.AddField(
            model_name="withdrawalconfig",
            name="wheel_stars_cost",
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name="withdrawalconfig",
            name="wheel_tbtc_cost",
            field=models.FloatField(default=100),
        ),
    ]
