# Generated by Django 5.1.4 on 2025-02-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_withdrawalconfig_wheel_kw_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="wheel_slot2",
            field=models.BooleanField(default=False),
        ),
    ]
