# Generated by Django 5.1.4 on 2025-02-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_userprofile_wheel_slot2"),
    ]

    operations = [
        migrations.AddField(
            model_name="autowithdrawalrequest",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="autowithdrawalrequest",
            name="wallet_address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="autowithdrawalrequest",
            name="status",
            field=models.CharField(default="wait_auto", max_length=255),
        ),
    ]
