# Generated by Django 5.1.4 on 2025-02-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_autowithdrawalrequest_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WheelStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount_kw", models.FloatField()),
                ("amount_tbtc", models.FloatField()),
                ("amount_stars", models.FloatField()),
                ("amount_nft", models.FloatField()),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserProfileWheelProxy",
            fields=[],
            options={
                "verbose_name": "User profile wheel stat",
                "verbose_name_plural": "User profiles wheel stats",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.userprofile",),
        ),
    ]
