# Generated by Django 5.1.4 on 2025-02-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_wheelstats_userprofilewheelproxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mining_was_stopped",
            field=models.BooleanField(default=False),
        ),
    ]
