# Generated by Django 5.1.4 on 2025-02-27 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_userprofile_mining_was_stopped"),
    ]

    operations = [
        migrations.CreateModel(
            name="StakingPeriodConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days", models.PositiveIntegerField()),
                ("apr", models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name="withdrawalconfig",
            name="max_auto_staking_out",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="withdrawalconfig",
            name="min_staking",
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name="withdrawalconfig",
            name="min_staking_out",
            field=models.FloatField(default=10),
        ),
        migrations.CreateModel(
            name="UserStaking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_amount", models.FloatField(blank=True, null=True)),
                ("reward", models.FloatField(blank=True, null=True)),
                ("collected", models.FloatField(default=0)),
                ("last_collected", models.DateTimeField(blank=True, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("days", models.PositiveIntegerField()),
                ("apr", models.FloatField()),
                ("wallet_address", models.CharField(default="", max_length=255)),
                ("tx_id", models.CharField(default="", max_length=255)),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                    ),
                ),
            ],
        ),
    ]
