# Generated by Django 5.1.4 on 2025-02-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_stakingperiodconfig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstaking",
            name="status",
            field=models.CharField(default="pending", max_length=255),
        ),
    ]
