# Generated by Django 5.1.4 on 2025-03-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_userstaking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="stop_mining_activate_last",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
