# Generated by Django 5.1.4 on 2025-03-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_userprofile_stop_mining_activate_last"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bonus_invest_level_1",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bonus_invest_level_2",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bring_bonus_invest_level_1",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bring_bonus_invest_level_2",
            field=models.FloatField(default=0),
        ),
    ]
