# Generated by Django 5.1.4 on 2025-03-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_userprofile_bonus_invest_level_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HashrateInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hashrate", models.FloatField(default=0)),
            ],
        ),
    ]
