# Generated by Django 5.1.4 on 2025-03-03 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_hashrateinfo"),
        ("tasks", "0015_alter_userreward_wallet"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoosterRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days_left", models.PositiveIntegerField()),
                ("old_price", models.FloatField()),
                ("new_price", models.FloatField()),
                ("total_amount", models.FloatField()),
                ("processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.booster"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                    ),
                ),
            ],
        ),
    ]
