# Generated by Django 5.1.4 on 2025-03-05 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_boosterrefund"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_staking_bonus_claimed_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
