# Generated by Django 5.1.4 on 2025-03-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_userprofile_last_staking_bonus_claimed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="magnit_buy_hashrate",
            field=models.FloatField(default=0),
        ),
    ]
