# Generated by Django 5.1.4 on 2025-03-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_userprofile_magnit_buy_hashrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="manager_buy_hashrate",
            field=models.FloatField(default=0),
        ),
    ]
