# Generated by Django 5.1.4 on 2025-03-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_userprofile_manager_buy_hashrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="blocked",
            field=models.BooleanField(default=False),
        ),
    ]
