# Generated by Django 5.1.4 on 2025-03-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_userprofile_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="genpowerstationconfig",
            name="duration",
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="storagepowerstationconfig",
            name="duration",
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="building_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
