# Generated by Django 5.1.4 on 2025-03-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_userprofile_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalconfig",
            name="tap_power",
            field=models.FloatField(default=0.5),
        ),
    ]
