# Generated by Django 5.1.4 on 2025-03-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_genpowerstationconfig_duration_and_more"),
        ("core", "0058_withdrawalconfig_tap_power"),
    ]

    operations = []
