# Generated by Django 5.1.4 on 2025-03-25 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_merge_20250323_1201"),
    ]

    operations = [
        migrations.CreateModel(
            name="NFTStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_type", models.CharField(max_length=50)),
                ("level", models.PositiveSmallIntegerField()),
                ("construction_time", models.DurationField()),
                ("active_image", models.ImageField(upload_to="stations/active/")),
                (
                    "construction_image",
                    models.ImageField(upload_to="stations/construction/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MintRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet", models.CharField(max_length=255)),
                ("nft_required", models.CharField(max_length=255)),
                ("nft_sent_1", models.CharField(blank=True, max_length=255, null=True)),
                ("nft_sent_2", models.CharField(blank=True, max_length=255, null=True)),
                ("kw_spent", models.FloatField()),
                ("tbtc_spent", models.FloatField()),
                ("status", models.CharField(default="pending", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StationRollbackLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_station", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("details", models.TextField()),
                ("status", models.CharField(default="success", max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                    ),
                ),
            ],
        ),
    ]
