# Generated by Django 5.1.4 on 2025-03-30 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_nftstation_mintrequest_stationrollbacklog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NFTRentalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_days", models.PositiveIntegerField(default=7)),
                ("max_days", models.PositiveIntegerField(default=60)),
                ("min_percentage", models.PositiveIntegerField(default=30)),
                ("max_percentage", models.PositiveIntegerField(default=70)),
                ("max_points_block", models.IntegerField(default=3)),
                ("platform_fee", models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.AlterModelOptions(
            name="genpowerstationconfig",
            options={"ordering": ["order_number"]},
        ),
        migrations.AlterModelOptions(
            name="storagepowerstationconfig",
            options={"ordering": ["order_number"]},
        ),
        migrations.AddField(
            model_name="genpowerstationconfig",
            name="order_number",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="storagepowerstationconfig",
            name="order_number",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="NFTRentalAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nft", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("owner_percentage", models.PositiveIntegerField()),
                ("platform_fee", models.PositiveIntegerField(default=5)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rented_nfts",
                        to="core.userprofile",
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rented_from",
                        to="core.userprofile",
                    ),
                ),
            ],
        ),
    ]
