# Generated by Django 5.1.4 on 2025-03-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_nftrentalconfig_alter_genpowerstationconfig_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mint_string",
            field=models.TextField(blank=True, default=""),
        ),
    ]
