# Generated by Django 5.1.4 on 2025-03-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_userprofile_mint_string"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationrollbacklog",
            name="energy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stationrollbacklog",
            name="engineer_level",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stationrollbacklog",
            name="generation_level",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stationrollbacklog",
            name="storage_level",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_mint",
            field=models.TextField(blank=True, default=""),
        ),
    ]
