# Generated by Django 5.1.4 on 2025-04-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_stationrollbacklog_energy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalconfig",
            name="gradation_minutes",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="withdrawalconfig",
            name="gradation_value",
            field=models.IntegerField(default=1),
        ),
    ]
