# Generated by Django 5.1.4 on 2025-04-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_stationnftowner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stationnftowner",
            name="nft",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
