# Generated by Django 5.1.4 on 2025-04-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_alter_notification_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="NFTDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nft", models.CharField(max_length=255)),
                ("hashrate", models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name="nftrentalagreement",
            name="hashrate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nftrentalagreement",
            name="rentals_days",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mining_last_stopped",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="points",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rent_blocked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nftrentalagreement",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nftrentalagreement",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
