# Generated by Django 5.1.4 on 2025-04-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_nftdatabase_nftrentalagreement_hashrate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalconfig",
            name="engineer_minus",
            field=models.IntegerField(default=1),
        ),
    ]
