# Generated by Django 5.1.4 on 2025-04-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_withdrawalconfig_engineer_minus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mintrequest",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("finished", "Finished")],
                default="pending",
                max_length=50,
            ),
        ),
    ]
