# Generated by Django 5.1.4 on 2025-04-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_alter_mintrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="nftdatabase",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="nftrentalagreement",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rent_mined_tokens_balance",
            field=models.FloatField(default=0),
        ),
    ]
