# Generated by Django 5.1.4 on 2025-04-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_nftdatabase_name_nftrentalagreement_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftrentalagreement',
            name='last_collected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalconfig',
            name='max_auto_rent',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='withdrawalconfig',
            name='min_rent',
            field=models.FloatField(default=10),
        ),
    ]
