# Generated by Django 5.1.4 on 2025-04-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_nftrentalagreement_last_collected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rent_farm_consumption_minus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rent_farm_consumption_plus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rent_total_mining_speed_minus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rent_total_mining_speed_plus',
            field=models.FloatField(default=0),
        ),
    ]
