# Generated by Django 5.1.4 on 2025-04-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_userprofile_rent_farm_consumption_minus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftdatabase',
            name='consumption_kw',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nftdatabase',
            name='mining_speed_tbtc',
            field=models.FloatField(default=0),
        ),
    ]
