# Generated by Django 5.1.4 on 2025-05-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_nftdatabase_consumption_kw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCommissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
