# Generated by Django 5.1.4 on 2025-05-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_rentalcommissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('station_power', 'Station Power'), ('network_hashrate', 'Network Hashrate'), ('active_stations', 'Active Stations'), ('active_asics', 'Active ASICs'), ('kw_price', 'kW Price'), ('tbtc_price', 'tBTC Price'), ('kw_mined', 'kW Mined'), ('tbtc_mined', 'tBTC Mined'), ('kw_per_tbtc', 'kW per tBTC'), ('energy_burned', 'Energy Burned'), ('tbtc_remaining', 'tBTC Remaining'), ('tbtc_staked', 'tBTC Staked')], max_length=50, verbose_name='Тип графика')),
                ('filter_type', models.CharField(choices=[('week', 'Week'), ('month', 'Month'), ('all_time', 'All Time')], max_length=10, verbose_name='Тип фильтра')),
                ('date', models.DateField(verbose_name='Дата')),
                ('value', models.FloatField(verbose_name='Значение')),
            ],
            options={
                'ordering': ['chart_type', 'filter_type', 'date'],
                'unique_together': {('chart_type', 'filter_type', 'date')},
            },
        ),
    ]
