# Generated by Django 5.1.4 on 2025-05-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_chartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_gold_sbt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_silver_sbt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='commision_percent',
            field=models.FloatField(default=0),
        ),
    ]
