# Generated by Django 5.1.4 on 2025-05-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_userprofile_has_gold_sbt_userprofile_has_silver_sbt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_gold_sbt_nft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_silver_sbt_nft',
            field=models.BooleanField(default=False),
        ),
    ]
