# Generated by Django 5.1.4 on 2025-05-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_userprofile_has_gold_sbt_nft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='azot_uses_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='powerbank_uses_left',
            field=models.IntegerField(default=0),
        ),
    ]
