# Generated by Django 5.1.4 on 2025-06-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_userprofile_azot_uses_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagepowerstationconfig',
            name='max_ton_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='storagepowerstationconfig',
            name='min_ton_price',
            field=models.FloatField(default=0),
        ),
    ]
