# Generated by Django 5.1.4 on 2025-06-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_storagepowerstationconfig_max_ton_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftrentalagreement',
            name='total_collected_owner',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nftrentalagreement',
            name='total_collected_renter',
            field=models.FloatField(default=0),
        ),
    ]
