# Generated by Django 5.1.4 on 2025-06-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_nftrentalagreement_total_collected_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftrentalagreement',
            name='mining_speed_tbtc',
            field=models.FloatField(default=0),
        ),
    ]
