# Generated by Django 5.1.4 on 2025-06-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_nftrentalagreement_mining_speed_tbtc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartdata',
            options={'ordering': ['chart_type', 'date']},
        ),
        migrations.AlterUniqueTogether(
            name='chartdata',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chartdata',
            name='filter_type',
        ),
    ]
