# Generated by Django 5.1.4 on 2025-06-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_chartdata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_energy', models.FloatField(default=0)),
                ('total_kw', models.FloatField(default=0)),
                ('total_tbtc', models.FloatField(default=0)),
                ('total_unclaimed_tbtc', models.FloatField(default=0)),
                ('total_ref_kw', models.FloatField(default=0)),
                ('total_ref_tbtc_mining', models.FloatField(default=0)),
                ('total_ref_tbtc_staking', models.FloatField(default=0)),
                ('total_mining_speed', models.FloatField(default=0)),
                ('actual_mining_speed', models.FloatField(default=0)),
                ('connected_asics', models.PositiveIntegerField(default=0)),
                ('mining_asics', models.PositiveIntegerField(default=0)),
                ('setup_asics', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Глобальна статистика',
                'verbose_name_plural': 'Глобальна статистика',
            },
        ),
    ]
