# Generated by Django 5.1.4 on 2025-06-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_globalstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('kw_deposit', models.FloatField(default=0, verbose_name='Поповнення kW')),
                ('tbtc_deposit', models.FloatField(default=0, verbose_name='Поповнення tBTC')),
                ('ref_kw_accrued', models.FloatField(default=0, verbose_name='Нараховано kW від рефералів')),
                ('ref_tbtc_mining_accrued', models.FloatField(default=0, verbose_name='Нараховано tBTC від рефералів (майнінг)')),
                ('ref_tbtc_staking_accrued', models.FloatField(default=0, verbose_name='Нараховано tBTC від рефералів (стейкінг)')),
                ('ref_kw_claimed', models.FloatField(default=0, verbose_name='Заклеймлено kW від рефералів')),
                ('ref_tbtc_mining_claimed', models.FloatField(default=0, verbose_name='Заклеймлено tBTC від рефералів (майнінг)')),
                ('ref_tbtc_staking_claimed', models.FloatField(default=0, verbose_name='Заклеймлено tBTC від рефералів (стейкінг)')),
            ],
            options={
                'verbose_name': 'Денна статистика',
                'verbose_name_plural': 'Денні статистики',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSpendStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_energy_accumulated', models.FloatField(default=0, verbose_name='Загальна накопичена Енергія')),
                ('energy_spent_build', models.FloatField(default=0, verbose_name='Витрачено Енергії на будівництво')),
                ('energy_spent_upgrade', models.FloatField(default=0, verbose_name='Витрачено Енергії на апгрейди')),
                ('energy_spent_engineer', models.FloatField(default=0, verbose_name='Витрачено Енергії на інженерів')),
                ('energy_spent_repair', models.FloatField(default=0, verbose_name='Витрачено Енергії на ремонти')),
                ('tbtc_spent_build', models.FloatField(default=0, verbose_name='Витрачено tBTC на будівництво')),
                ('tbtc_spent_upgrade', models.FloatField(default=0, verbose_name='Витрачено tBTC на апгрейди')),
            ],
            options={
                'verbose_name': 'Глобальна статистика витрат',
                'verbose_name_plural': 'Глобальна статистика витрат',
            },
        ),
    ]
