# Generated by Django 5.1.4 on 2025-06-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_dailystats_globalspendstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalStats',
        ),
    ]
