# Generated by Django 5.1.4 on 2025-06-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_globalspendstats_tbtc_spent_repair'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Дата')),
                ('stat_type', models.CharField(choices=[('kw_deposit', 'Поповнення kW'), ('tbtc_deposit', 'Поповнення tBTC'), ('ref_kw_accrued', 'Нараховано kW від рефералів'), ('ref_tbtc_mining_accrued', 'Нараховано tBTC від рефералів (майнінг)'), ('ref_tbtc_staking_accrued', 'Нараховано tBTC від рефералів (стейкінг)'), ('ref_kw_claimed', 'Заклеймлено kW від рефералів'), ('ref_tbtc_mining_claimed', 'Заклеймлено tBTC від рефералів (майнінг)'), ('ref_tbtc_staking_claimed', 'Заклеймлено tBTC від рефералів (стейкінг)')], max_length=50, verbose_name='Тип')),
                ('value', models.FloatField(default=0, verbose_name='Значення')),
            ],
            options={
                'verbose_name': 'Статистика поповнення',
                'verbose_name_plural': 'Статистика поповнення',
                'ordering': ['-date', 'stat_type'],
            },
        ),
        migrations.CreateModel(
            name='JarvisEnergyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('total_jarvis_energy', models.FloatField(default=0, verbose_name='Загальна натапана Енергія Джарвісом')),
                ('jarvis_level_1', models.FloatField(default=0, verbose_name='Джарвіс рівня 1')),
                ('jarvis_level_2', models.FloatField(default=0, verbose_name='Джарвіс рівня 2')),
                ('jarvis_level_3', models.FloatField(default=0, verbose_name='Джарвіс рівня 3')),
                ('jarvis_level_4', models.FloatField(default=0, verbose_name='Джарвіс рівня 4')),
                ('jarvis_level_5', models.FloatField(default=0, verbose_name='Джарвіс рівня 5')),
            ],
            options={
                'verbose_name': 'Енергія Джарвіса за день',
                'verbose_name_plural': 'Енергія Джарвіса за день',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MiningStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tbtc_mined', models.FloatField(default=0, verbose_name='Загальна кількість добутого tBTC')),
                ('total_tbtc_claimed', models.FloatField(default=0, verbose_name='Загальна кількість заклеймленого tBTC')),
                ('energy_spent_mining', models.FloatField(default=0, verbose_name='Витрачено Енергії на майнінг')),
                ('energy_saved_powerbank', models.FloatField(default=0, verbose_name='Зекономлено Енергії на майнінг (PowerBank)')),
                ('energy_saved_magnet', models.FloatField(default=0, verbose_name='Зекономлено Енергії на майнінг (Магніт)')),
            ],
            options={
                'verbose_name': 'Глобальна статистика майнінгу',
                'verbose_name_plural': 'Глобальна статистика майнінгу',
            },
        ),
        migrations.CreateModel(
            name='StationLevelStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_10_3', models.PositiveIntegerField(default=0, verbose_name='10-3')),
                ('count_10_2', models.PositiveIntegerField(default=0, verbose_name='10-2')),
                ('count_10_1', models.PositiveIntegerField(default=0, verbose_name='10-1')),
                ('count_9_3', models.PositiveIntegerField(default=0, verbose_name='9-3')),
                ('count_9_2', models.PositiveIntegerField(default=0, verbose_name='9-2')),
                ('count_9_1', models.PositiveIntegerField(default=0, verbose_name='9-1')),
                ('count_8_3', models.PositiveIntegerField(default=0, verbose_name='8-3')),
                ('count_8_2', models.PositiveIntegerField(default=0, verbose_name='8-2')),
                ('count_8_1', models.PositiveIntegerField(default=0, verbose_name='8-1')),
                ('count_7_3', models.PositiveIntegerField(default=0, verbose_name='7-3')),
                ('count_7_2', models.PositiveIntegerField(default=0, verbose_name='7-2')),
                ('count_7_1', models.PositiveIntegerField(default=0, verbose_name='7-1')),
                ('count_6_3', models.PositiveIntegerField(default=0, verbose_name='6-3')),
                ('count_6_2', models.PositiveIntegerField(default=0, verbose_name='6-2')),
                ('count_6_1', models.PositiveIntegerField(default=0, verbose_name='6-1')),
                ('count_5_3', models.PositiveIntegerField(default=0, verbose_name='5-3')),
                ('count_5_2', models.PositiveIntegerField(default=0, verbose_name='5-2')),
                ('count_5_1', models.PositiveIntegerField(default=0, verbose_name='5-1')),
                ('count_4_3', models.PositiveIntegerField(default=0, verbose_name='4-3')),
                ('count_4_2', models.PositiveIntegerField(default=0, verbose_name='4-2')),
                ('count_4_1', models.PositiveIntegerField(default=0, verbose_name='4-1')),
                ('count_3_3', models.PositiveIntegerField(default=0, verbose_name='3-3')),
                ('count_3_2', models.PositiveIntegerField(default=0, verbose_name='3-2')),
                ('count_3_1', models.PositiveIntegerField(default=0, verbose_name='3-1')),
                ('count_2_3', models.PositiveIntegerField(default=0, verbose_name='2-3')),
                ('count_2_2', models.PositiveIntegerField(default=0, verbose_name='2-2')),
                ('count_2_1', models.PositiveIntegerField(default=0, verbose_name='2-1')),
                ('count_1_3', models.PositiveIntegerField(default=0, verbose_name='1-3')),
                ('count_1_2', models.PositiveIntegerField(default=0, verbose_name='1-2')),
                ('count_1_1', models.PositiveIntegerField(default=0, verbose_name='1-1')),
            ],
            options={
                'verbose_name': 'Статистика станцій за рівнями',
                'verbose_name_plural': 'Статистика станцій за рівнями',
            },
        ),
        migrations.DeleteModel(
            name='DailyStats',
        ),
    ]
