# Generated by Django 5.1.4 on 2025-07-02 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_dailystat_jarvisenergystat_miningstats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mined_tokens_balance_s21",
            field=models.FloatField(default=0, verbose_name="Баланс майнінгу S21"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mined_tokens_balance_sx",
            field=models.FloatField(default=0, verbose_name="Баланс майнінгу SX"),
        ),
        migrations.CreateModel(
            name="SpecialAsicStaking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        choices=[(30, "30 днів"), (90, "90 днів"), (180, "180 днів")]
                    ),
                ),
                ("apr", models.FloatField(verbose_name="APR %")),
                (
                    "accumulated_balance",
                    models.FloatField(default=0, verbose_name="Накопичений баланс"),
                ),
                (
                    "staked_amount",
                    models.FloatField(default=0, verbose_name="Сума в стейкінгу"),
                ),
                (
                    "earned_amount",
                    models.FloatField(default=0, verbose_name="Нараховані відсотки"),
                ),
                (
                    "accumulation_start",
                    models.DateTimeField(verbose_name="Початок накопичення"),
                ),
                (
                    "staking_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Початок стейкінгу"
                    ),
                ),
                (
                    "staking_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Кінець стейкінгу"
                    ),
                ),
                ("last_calculated", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accumulating", "Накопичення"),
                            ("active", "Активний"),
                            ("completed", "Завершений"),
                            ("withdrawn", "Виведений"),
                        ],
                        default="accumulating",
                        max_length=20,
                    ),
                ),
                (
                    "cycle_number",
                    models.PositiveIntegerField(default=1, verbose_name="Номер циклу"),
                ),
                (
                    "qualifying_asics",
                    models.TextField(
                        blank=True, verbose_name="Асики S21/SX в момент старту"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Спеціальний стейкінг S21/SX",
                "verbose_name_plural": "Спеціальні стейкінги S21/SX",
            },
        ),
    ]
