# Generated by Django 5.1.4 on 2025-07-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0091_userprofile_mined_tokens_balance_s21_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialasicstaking",
            name="accumulated_balance",
        ),
        migrations.RemoveField(
            model_name="specialasicstaking",
            name="accumulation_start",
        ),
        migrations.RemoveField(
            model_name="specialasicstaking",
            name="cycle_number",
        ),
        migrations.RemoveField(
            model_name="specialasicstaking",
            name="duration_days",
        ),
        migrations.RemoveField(
            model_name="specialasicstaking",
            name="earned_amount",
        ),
        migrations.RemoveField(
            model_name="specialasicstaking",
            name="last_calculated",
        ),
        migrations.RemoveField(
            model_name="specialasicstaking",
            name="qualifying_asics",
        ),
        migrations.RemoveField(
            model_name="specialasicstaking",
            name="staked_amount",
        ),
        migrations.RemoveField(
            model_name="specialasicstaking",
            name="staking_end",
        ),
        migrations.RemoveField(
            model_name="specialasicstaking",
            name="staking_start",
        ),
        migrations.AddField(
            model_name="specialasicstaking",
            name="days",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="specialasicstaking",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="specialasicstaking",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="specialasicstaking",
            name="token_amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="specialasicstaking",
            name="apr",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="specialasicstaking",
            name="status",
            field=models.CharField(default="pending", max_length=255),
        ),
    ]
