# Generated by Django 5.1.4 on 2025-07-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0092_remove_specialasicstaking_accumulated_balance_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialasicstaking",
            options={},
        ),
    ]
