# Generated by Django 5.1.4 on 2025-07-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0093_alter_specialasicstaking_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialasicstaking",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("finished", "Finished")],
                default="pending",
                max_length=255,
            ),
        ),
    ]
