# Generated by Django 5.1.4 on 2025-07-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0094_alter_specialasicstaking_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BurnedTBTCBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet",
                    models.CharField(max_length=255, verbose_name="Wallet Address"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=9, max_digits=20, verbose_name="Amount"
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Upload Date"),
                ),
            ],
            options={
                "verbose_name": "Burned tBTC Base Record",
                "verbose_name_plural": "Burned tBTC Base",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="past_engineer_level",
            field=models.IntegerField(default=0),
        ),
    ]
