# Generated by Django 5.1.4 on 2025-07-06 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_burnedtbtcbase_userprofile_past_engineer_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burnedtbtcbase',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
        migrations.CreateModel(
            name='UserBurnedTBTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=255, verbose_name='Wallet Address')),
                ('amount', models.FloatField(verbose_name='Total Amount')),
                ('apr', models.FloatField(default=24, verbose_name='APR %')),
                ('unlock_date_1', models.DateField(blank=True, null=True, verbose_name='Unlock Date 1')),
                ('unlock_date_2', models.DateField(blank=True, null=True, verbose_name='Unlock Date 2')),
                ('unlock_date_3', models.DateField(blank=True, null=True, verbose_name='Unlock Date 3')),
                ('unlock_date_4', models.DateField(blank=True, null=True, verbose_name='Unlock Date 4')),
                ('unlock_date_5', models.DateField(blank=True, null=True, verbose_name='Unlock Date 5')),
                ('unlock_date_6', models.DateField(blank=True, null=True, verbose_name='Unlock Date 6')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', verbose_name='User')),
            ],
        ),
    ]
