# Generated by Django 5.1.4 on 2025-07-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_alter_burnedtbtcbase_amount_userburnedtbtc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_hydro_station',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hydro_prev_engineer_level',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hydro_prev_generation_level',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hydro_prev_station_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hydro_prev_storage_level',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
