# Generated by Django 5.1.4 on 2025-07-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_userprofile_has_hydro_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hydro_prev_energy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hydro_prev_engineer_level',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hydro_prev_generation_level',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hydro_prev_storage_level',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
