# Generated by Django 5.1.4 on 2025-07-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_userprofile_hydro_prev_energy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва пункту'),
        ),
        migrations.AddField(
            model_name='roadmapitem',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва пункту'),
        ),
    ]
