# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_roadmapitem_title_en_roadmapitem_title_ru"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalconfig",
            name="min_inapp_kw",
            field=models.FloatField(
                default=300,
                help_text="Минимальная сумма kW для вывода In-App",
                verbose_name="Min in-app kw",
            ),
        ),
        migrations.AddField(
            model_name="withdrawalconfig",
            name="min_inapp_tbtc",
            field=models.FloatField(
                default=50,
                help_text="Минимальная сумма fBTC для вывода In-App",
                verbose_name="Min in-app tbtc",
            ),
        ),
    ]
