# Generated by Django 5.1.4 on 2025-07-18 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_roadmapitem_title_en_roadmapitem_title_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва пункту EN'),
        ),
        migrations.AlterField(
            model_name='roadmapitem',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва пункту RU'),
        ),
        migrations.CreateModel(
            name='LinkedUserNFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=255, verbose_name='Wallet Address')),
                ('nft_address', models.CharField(max_length=255, verbose_name='NFT Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', verbose_name='User')),
            ],
        ),
    ]
