# Generated by Django 5.1.4 on 2025-07-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_alter_roadmapitem_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedusernft',
            name='user',
        ),
    ]
