# Generated by Django 5.1.4 on 2025-07-18 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_remove_linkedusernft_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedusernft',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', verbose_name='User'),
        ),
    ]
