# Generated by Django 5.1.4 on 2025-07-24 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_linkedusernft_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='NFT Name')),
                ('gradation_minutes', models.IntegerField(default=10)),
                ('gradation_value', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TimedUserNFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=255, verbose_name='Wallet Address')),
                ('name', models.CharField(max_length=255, verbose_name='NFT Name')),
                ('collection', models.CharField(max_length=255, verbose_name='NFT Collection')),
                ('nft_address', models.CharField(max_length=255, verbose_name='NFT Address')),
                ('block_until', models.DateTimeField(blank=True, null=True, verbose_name='Block Until')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='WalletInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=255, verbose_name='Wallet Address')),
                ('kw_amount', models.FloatField(default=0)),
                ('tbtc_amount', models.FloatField(default=0)),
                ('block_until', models.DateTimeField(blank=True, null=True, verbose_name='Block Until')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', verbose_name='User')),
            ],
        ),
    ]
