# Generated by Django 5.1.4 on 2025-07-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_gradationconfig_timedusernft_walletinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradationconfig',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
