# Generated by Django 5.1.4 on 2025-07-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_alter_gradationconfig_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='electrics_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_sub_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
