# Generated by Django 5.1.4 on 2025-07-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_userprofile_electrics_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerconfig',
            name='hire_cost_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nftdatabase',
            name='wallet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
