# Generated by Django 5.1.4 on 2025-07-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_engineerconfig_hire_cost_stars_nftdatabase_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletinfo',
            name='tbtc_amount_s21',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='walletinfo',
            name='tbtc_amount_sx',
            field=models.FloatField(default=0),
        ),
    ]
