# Generated by Django 5.1.4 on 2025-08-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_walletinfo_tbtc_amount_s21_walletinfo_tbtc_amount_sx'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prev_ton_wallet',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
