# Generated by Django 5.1.4 on 2025-08-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_userprofile_prev_ton_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='powerbank_reward_balance',
            field=models.IntegerField(default=0),
        ),
    ]
