# Generated by Django 5.1.4 on 2025-08-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_userprofile_powerbank_reward_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='azot_reward_balance',
            field=models.IntegerField(default=0),
        ),
    ]
