# Generated by Django 5.1.4 on 2025-08-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_userprofile_azot_reward_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_orbital_station',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='orbital_first_owner',
            field=models.BooleanField(default=False),
        ),
    ]
