# Generated by Django 5.1.4 on 2025-08-19 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_userprofile_has_orbital_station_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationUpgradeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50, verbose_name='Рівень станції')),
                ('upgrade_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата апгрейду')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
            options={
                'verbose_name': 'Подія апгрейду станції',
                'verbose_name_plural': 'Події апгрейду станцій',
            },
        ),
    ]
