# Generated by Django 5.1.4 on 2025-08-20 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_stationupgradeevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='orbital_is_blue',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrbitalOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_address', models.CharField(max_length=255, verbose_name='NFT Address')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', verbose_name='User')),
            ],
        ),
    ]
