# Generated by Django 5.1.4 on 2025-08-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_userprofile_orbital_is_blue_orbitalowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_station_nft',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
