# Generated by Django 5.1.4 on 2025-08-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_userprofile_current_station_nft'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftdatabase',
            name='collection',
            field=models.CharField(default='', max_length=255, verbose_name='NFT Collection'),
        ),
        migrations.AlterField(
            model_name='nftdatabase',
            name='hashrate',
            field=models.FloatField(default=0),
        ),
    ]
