# Generated by Django 5.1.4 on 2025-08-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_nftdatabase_collection_alter_nftdatabase_hashrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='orbital_force_basic',
            field=models.BooleanField(default=False),
        ),
    ]
