# Generated by Django 5.1.4 on 2025-08-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_userprofile_orbital_force_basic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hydro_prev_power',
            field=models.FloatField(default=100),
        ),
    ]
