# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_userprofile_energy_run_last_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerconfig',
            name='saved_percent_on_lose',
            field=models.FloatField(
                default=0,
                help_text='Процент энергии (kW), сохраняемой при проигрыше забега для этого уровня инженера (0–100)',
            ),
        ),
    ]
