# Generated by Django 5.1.4 on 2025-02-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.FloatField()),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="task_icons/"),
                ),
                ("title", models.CharField(max_length=200)),
                ("modal_description", models.TextField()),
                ("modal_button_text", models.CharField(max_length=100)),
                (
                    "dependency",
                    models.CharField(
                        choices=[
                            ("player", "Гравець"),
                            ("referral", "Реферал"),
                            ("station", "Станція"),
                            ("storage", "Рівень Storage"),
                            ("generation", "Рівень Generation"),
                            ("balance_energizer", "Balance Energizer"),
                            ("balance_kW", "Balance ingame wallet kW"),
                            ("balance_tBTC", "Balance ingame wallet tBTC"),
                            ("subscribed_channel", "Підписка на канал"),
                            ("chat_message", "Повідомлення в чаті"),
                            ("nft_asic", "NFT ASIC"),
                            ("roulette", "Рулетка"),
                        ],
                        max_length=50,
                    ),
                ),
                ("condition", models.CharField(max_length=200)),
                (
                    "reward_type",
                    models.CharField(
                        choices=[("kW", "kW"), ("tBTC", "tBTC")], max_length=10
                    ),
                ),
                ("reward_amount", models.FloatField()),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="tasks.taskcategory"),
                ),
            ],
            options={
                "ordering": ["order_number"],
            },
        ),
    ]
