# Generated by Django 5.1.4 on 2025-02-11 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_withdrawalrequest_is_auto"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="dependency",
        ),
        migrations.AddField(
            model_name="task",
            name="n1",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="task",
            name="n2",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="task",
            name="n3",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="task",
            name="condition",
            field=models.CharField(
                choices=[
                    ("referral_station", "Реферали | >= n1 шт. | Станція >= n2 рівня"),
                    ("station", "Юзер | Станція >= n1 рівня"),
                    ("storage", "Юзер | Станція >= n1 рівня і Storage >= n2 "),
                    ("generation", "Юзер | Станція >= n1 рівня і Generation >= n2"),
                    ("balance_energizer", "Юзер | Баланс Energizer >= n1"),
                    ("balance_kW", "Юзер | Balance ingame wallet kW >= n1"),
                    ("balance_tBTC", "Юзер | Balance ingame wallet tBTC >= n1"),
                    ("subscribed_channel", "Юзер | Підписка на канал"),
                    ("chat_message", "Юзер | Повідомлення в чаті"),
                    ("nft_asic", "Юзер | NFT ASIC кількість >= n1"),
                    ("roulette", "Юзер | Рулетка"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="UserTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("claimed", models.BooleanField(default=False)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "task")},
            },
        ),
    ]
