# Generated by Django 5.1.4 on 2025-02-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_remove_task_dependency_task_n1_task_n2_task_n3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="n1",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="task",
            name="n2",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="task",
            name="n3",
            field=models.TextField(blank=True, default=""),
        ),
    ]
