# Generated by Django 5.1.4 on 2025-02-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_n1_alter_task_n2_alter_task_n3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="icon",
            field=models.FileField(blank=True, null=True, upload_to="task_icons/"),
        ),
    ]
