# Generated by Django 5.1.4 on 2025-02-12 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_withdrawalrequest_is_auto"),
        ("tasks", "0004_alter_task_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="WheelSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[("superprize", "Superprize"), ("regular", "Regular")],
                        max_length=20,
                    ),
                ),
                (
                    "asset_name",
                    models.CharField(
                        choices=[
                            ("kW", "kW"),
                            ("tBTC", "tBTC"),
                            ("ASIC", "ASIC"),
                            ("Stars", "Stars"),
                            ("Chip", "Chip"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "asset_image",
                    models.FileField(blank=True, null=True, upload_to="wheel_assets/"),
                ),
                ("n_parameter", models.TextField(blank=True, null=True)),
                ("asset_quantity", models.FloatField(blank=True, null=True)),
                ("probability_kW", models.FloatField()),
                ("probability_tBTC", models.FloatField()),
                ("probability_stars", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="UserReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("kW", "kW"),
                            ("tBTC", "tBTC"),
                            ("ASIC", "ASIC"),
                            ("Stars", "Stars"),
                            ("Chip", "Chip"),
                        ],
                        max_length=50,
                    ),
                ),
                ("n_parameter", models.TextField(blank=True, null=True)),
                ("asset_quantity", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unclaimed", "Неотриманий"),
                            ("processing", "В обробці"),
                            ("claimed", "Отриманий"),
                        ],
                        default="unclaimed",
                        max_length=20,
                    ),
                ),
                (
                    "processing_type",
                    models.CharField(
                        choices=[("automatic", "Автоматичне"), ("manual", "Ручне")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("random_val", models.FloatField(blank=True, null=True)),
                ("paid_with", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
