# Generated by Django 5.1.4 on 2025-02-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_wheelslot_userreward"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertask",
            name="started",
            field=models.BooleanField(default=False),
        ),
    ]
