# Generated by Django 5.1.4 on 2025-02-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_usertask_started"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.FloatField()),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("azot", "Жидкий азот"),
                            ("jarvis", "J.A.R.V.I.S. Бот"),
                            ("cryo", "Криокамера"),
                            ("powerbank", "PowerBank"),
                            ("magnit", "Магнит на счетчик"),
                            ("asic_manager", "ASIC Менеджер"),
                        ],
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "icon",
                    models.FileField(blank=True, null=True, upload_to="booster_icons/"),
                ),
                ("status1", models.CharField(blank=True, max_length=100)),
                ("status2", models.CharField(blank=True, max_length=100)),
                ("additional_info1", models.TextField(blank=True)),
                ("additional_info2", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("popup", models.TextField(blank=True)),
                (
                    "first_free",
                    models.CharField(
                        choices=[("free", "Free"), ("nofree", "No free")], max_length=10
                    ),
                ),
                ("price1", models.IntegerField()),
                ("price2", models.IntegerField()),
                ("price3", models.IntegerField()),
                ("price4", models.IntegerField()),
                ("price5", models.IntegerField()),
                ("price6", models.IntegerField()),
                ("price7", models.IntegerField()),
                ("n1", models.TextField(blank=True, default="")),
                ("n2", models.TextField(blank=True, default="")),
                ("n3", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["order_number"],
            },
        ),
    ]
