# Generated by Django 5.1.4 on 2025-02-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_booster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booster",
            name="slug",
            field=models.CharField(
                choices=[
                    ("azot", "Жидкий азот"),
                    ("jarvis", "J.A.R.V.I.S. Бот - собирает n1 % энергии"),
                    ("cryo", "Криокамера"),
                    ("powerbank", "PowerBank"),
                    ("magnit", "Магнит на счетчик - снижание на n1 %"),
                    ("asic_manager", "ASIC Менеджер - остановка от 1 до n1 раз"),
                ],
                max_length=100,
            ),
        ),
    ]
