# Generated by Django 5.1.4 on 2025-02-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_alter_booster_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booster",
            name="first_free",
        ),
        migrations.AlterField(
            model_name="booster",
            name="slug",
            field=models.CharField(
                choices=[
                    ("azot", "Жидкий азот - +n1 за каждую активацию"),
                    ("jarvis", "J.A.R.V.I.S. Бот - собирает n1% энергии"),
                    ("cryo", "Криокамера"),
                    ("powerbank", "PowerBank"),
                    ("magnit", "Магнит на счетчик - снижание на n1%"),
                    ("asic_manager", "ASIC Менеджер - остановка от 1 до n1 раз"),
                ],
                max_length=100,
            ),
        ),
    ]
