# Generated by Django 5.1.4 on 2025-02-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_remove_booster_first_free_alter_booster_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booster",
            name="slug",
            field=models.CharField(
                choices=[
                    ("azot", "Жидкий азот | +n1 за каждую активацию"),
                    ("jarvis", "J.A.R.V.I.S. Бот | собирает n1% энергии"),
                    ("cryo", "Криокамера"),
                    ("autostart", "Автостартер"),
                    ("powerbank", "PowerBank | доступен раз в n1 часов"),
                    ("magnit", "Магнит на счетчик | снижание на n1%"),
                    (
                        "asic_manager",
                        "ASIC Менеджер | остановка от 1 до n1 (макс. 3) раз",
                    ),
                ],
                max_length=100,
            ),
        ),
    ]
