# Generated by Django 5.1.4 on 2025-02-19 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_alter_booster_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreward",
            name="slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.wheelslot",
            ),
        ),
    ]
