# Generated by Django 5.1.4 on 2025-02-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_userreward_slot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wheelslot",
            options={"ordering": ["order_number"]},
        ),
        migrations.AddField(
            model_name="wheelslot",
            name="order_number",
            field=models.FloatField(default=0),
        ),
    ]
