# Generated by Django 5.1.4 on 2025-02-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_alter_wheelslot_options_wheelslot_order_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="WheelSlot2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.FloatField(default=0)),
                (
                    "color",
                    models.CharField(
                        choices=[("superprize", "Superprize"), ("regular", "Regular")],
                        max_length=20,
                    ),
                ),
                (
                    "asset_name",
                    models.CharField(
                        choices=[
                            ("kW", "kW"),
                            ("tBTC", "tBTC"),
                            ("ASIC", "ASIC"),
                            ("Stars", "Stars"),
                            ("Chip", "Chip"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "asset_image",
                    models.FileField(blank=True, null=True, upload_to="wheel_assets/"),
                ),
                ("n_parameter", models.TextField(blank=True, null=True)),
                ("asset_quantity", models.FloatField(blank=True, null=True)),
                ("probability_kW", models.FloatField()),
                ("probability_tBTC", models.FloatField()),
                ("probability_stars", models.FloatField()),
            ],
            options={
                "ordering": ["order_number"],
            },
        ),
    ]
