# Generated by Django 5.1.4 on 2025-02-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0013_wheelslot2"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreward",
            name="wallet",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
