# Generated by Django 5.1.4 on 2025-02-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_userreward_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreward',
            name='wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
