# Generated by Django 5.1.4 on 2025-05-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_userreward_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='price10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booster',
            name='price8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booster',
            name='price9',
            field=models.IntegerField(default=0),
        ),
    ]
