# Generated by Django 5.1.4 on 2025-07-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_booster_price10_booster_price8_booster_price9'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='additional_info1_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booster',
            name='additional_info1_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booster',
            name='additional_info2_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booster',
            name='additional_info2_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booster',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booster',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booster',
            name='popup_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booster',
            name='popup_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booster',
            name='status1_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booster',
            name='status1_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booster',
            name='status2_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booster',
            name='status2_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booster',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='booster',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
