# Generated by Django 5.1.4 on 2025-07-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_booster_additional_info1_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='price10_fbtc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booster',
            name='price1_fbtc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booster',
            name='price2_fbtc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booster',
            name='price3_fbtc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booster',
            name='price4_fbtc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booster',
            name='price5_fbtc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booster',
            name='price6_fbtc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booster',
            name='price7_fbtc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booster',
            name='price8_fbtc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booster',
            name='price9_fbtc',
            field=models.FloatField(default=0),
        ),
    ]
