# Generated by Django 5.1.4 on 2025-07-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_booster_price10_fbtc_booster_price1_fbtc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='modal_button_text_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='modal_button_text_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='modal_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='modal_description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
