# Generated by Django 5.1.4 on 2025-08-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_booster_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreward',
            name='asset_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userreward',
            name='asset_type',
            field=models.CharField(choices=[('autostart', 'Автостартер'), ('azot', 'Жидкий азот'), ('powerbank', 'Павер Банк'), ('magnit', 'Магніт'), ('asic_manager', 'Асик Менеджер'), ('electrics', 'Інженер'), ('jarvis', 'Джарвіс'), ('ASIC', 'ASIC'), ('kW', 'kW'), ('tBTC', 'tBTC'), ('Stars', 'Stars'), ('Chip', 'Chip')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wheelslot',
            name='asset_name',
            field=models.CharField(choices=[('kW', 'kW'), ('tBTC', 'tBTC'), ('ASIC', 'ASIC'), ('Stars', 'Stars'), ('Chip', 'Chip'), ('autostart', 'Автостартер'), ('azot', 'Жидкий азот'), ('powerbank', 'Павер Банк'), ('magnit', 'Магніт'), ('asic_manager', 'Асик Менеджер'), ('electrics', 'Інженер'), ('jarvis', 'Джарвіс')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wheelslot2',
            name='asset_name',
            field=models.CharField(choices=[('kW', 'kW'), ('tBTC', 'tBTC'), ('ASIC', 'ASIC'), ('Stars', 'Stars'), ('Chip', 'Chip'), ('autostart', 'Автостартер'), ('azot', 'Жидкий азот'), ('powerbank', 'Павер Банк'), ('magnit', 'Магніт'), ('asic_manager', 'Асик Менеджер'), ('electrics', 'Інженер'), ('jarvis', 'Джарвіс')], max_length=50),
        ),
    ]
