# Generated by Django 5.1.4 on 2025-08-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_userreward_asset_days_alter_userreward_asset_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreward',
            name='asset_days',
        ),
        migrations.AlterField(
            model_name='userreward',
            name='asset_type',
            field=models.CharField(choices=[('kW', 'kW'), ('tBTC', 'tBTC'), ('ASIC', 'ASIC'), ('Stars', 'Stars'), ('Chip', 'Chip'), ('autostart', 'Автостартер'), ('azot', 'Жидкий азот'), ('powerbank', 'Павер Банк'), ('magnit', 'Магніт'), ('asic_manager', 'Асик Менеджер'), ('electrics', 'Інженер'), ('jarvis', 'Джарвіс')], max_length=50),
        ),
    ]
