# Generated by Django 5.1.4 on 2025-08-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_remove_userreward_asset_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRewardReport',
            fields=[
            ],
            options={
                'verbose_name': 'UserReward Report',
                'verbose_name_plural': 'UserReward Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.userreward',),
        ),
    ]
