"""
Django settings for tonbtc project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Load environment variables from the .env file in the root directory
load_dotenv(override=True)
BOT_TOKEN = os.getenv("BOT_TOKEN")
APP_URL = os.getenv("APP_URL")
WEBHOOK_URL = os.getenv("WEBHOOK_URL")

import base64
import hashlib

from cryptography.fernet import Fernet


def generate_key(password: str) -> bytes:
    return base64.urlsafe_b64encode(hashlib.sha256(password.encode()).digest())


def encrypt_seed(seed_phrase: str, password: str) -> str:
    key = generate_key(password)
    fernet = Fernet(key)
    encrypted = fernet.encrypt(seed_phrase.encode())
    return encrypted.decode()


def decrypt_seed(encrypted_seed: str, password: str) -> str:
    key = generate_key(password)
    fernet = Fernet(key)
    decrypted = fernet.decrypt(encrypted_seed.encode())
    return decrypted.decode()


PASS = os.getenv("PASS")

KW_MNEMONICS_SECRET = decrypt_seed(os.getenv("KW_MNEMONICS_SECRET"), PASS)
TBTC_MNEMONICS_SECRET = decrypt_seed(os.getenv("TBTC_MNEMONICS_SECRET"), PASS)
STAKING_MNEMONICS_SECRET = decrypt_seed(os.getenv("STAKING_MNEMONICS_SECRET"), PASS)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes", "on")

ALLOWED_HOSTS = ["*"]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
    "https://tbtc.one",
    "https://mine.tbtc.one",
]

from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = (
    *default_headers,
    "X-Custom-Token",
)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "corsheaders",
    "rest_framework",
    "core",
    "tasks",
    "drf_yasg",
    "django_filters",
    "tgbot",
    # "django_celery_beat",
    # "django_celery_results",
    "rangefilter",
    # "django_filters",
    # "debug_toolbar",
    'import_export'
]

MIDDLEWARE = [
    # "debug_toolbar.middleware.DebugToolbarMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tonbtc.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tonbtc.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import dj_database_url

DATABASES = {"default": {**dj_database_url.parse(os.getenv("DB_URL")), "CONN_MAX_AGE": 60}}

# python manage.py dumpdata > datadump.json
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "uk"

TIME_ZONE = "Europe/Kyiv"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_CLASSES": [
       "core.thro.CustomUserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "custom_user": "250/min",  # увеличено до 250 для оптимального UX
    },
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
}

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "X-Custom-Token": {"type": "apiKey", "name": "X-Custom-Token", "in": "header"}
    }
}

# Celery settings
CELERY_BROKER_URL = "redis://:mj8WZWeX1ThWuYF@127.0.0.1:6379"
CELERY_RESULT_BACKEND = "django-db"
CELERY_BEAT_SCHEDULE = {
    # "generate_energy": {
    #     "task": "core.tasks.generate_energy_task",
    #     "schedule": timedelta(seconds=60),
    # },
    # "check_transactions": {
    #     "task": "core.tasks.check_transactions",
    #     "schedule": timedelta(seconds=10),
    # },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://:mj8WZWeX1ThWuYF@127.0.0.1:6379",
    }
}

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    "188.163.114.168",
    # ...
]

IS_PRODUCTION = os.getenv("IS_PRODUCTION", "False") == "True"

STATIC_URL = "/static/"
MEDIA_URL = "/api/media/"

# if IS_PRODUCTION:
#     STATIC_ROOT = Path("/srv/tbtc/static")
#     MEDIA_ROOT = Path("/srv/tbtc/media")
# else:
STATIC_ROOT = "static"
MEDIA_ROOT = BASE_DIR / "media"
    


# import sentry_sdk

# sentry_sdk.init(
#     dsn="https://6ae55ec4f0cd696a1b685373af0291d9@o4509672601354240.ingest.de.sentry.io/4509672603910224",
#     # Add data like request headers and IP for users,
#     # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
#     send_default_pii=True,
#     # Set traces_sample_rate to 1.0 to capture 100%
#     # of transactions for tracing.
#     traces_sample_rate=1.0,
#     # Set profile_session_sample_rate to 1.0 to profile 100%
#     # of profile sessions.
#     profile_session_sample_rate=1.0,
#     # Set profile_lifecycle to "trace" to automatically
#     # run the profiler on when there is an active transaction
#     profile_lifecycle="trace",
# )